/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SmartHomeUiModule extends AbstractSmartHomeUiModule {
  public SmartHomeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
