/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.smarthome.parser.antlr.internal.InternalSmartHomeParser;
import org.xtext.example.smarthome.services.SmartHomeGrammarAccess;

public class SmartHomeParser extends AbstractAntlrParser {

	@Inject
	private SmartHomeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmartHomeParser createParser(XtextTokenStream stream) {
		return new InternalSmartHomeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Controller";
	}

	public SmartHomeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartHomeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
