/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmartHomeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/smarthome/parser/antlr/internal/InternalSmartHome.tokens");
	}
}
