/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.smarthome.services.SmartHomeGrammarAccess;

@SuppressWarnings("all")
public class SmartHomeSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SmartHomeGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Device_ActionsKeyword_5_q;
	protected AbstractElementAlias match_Device_ConstraintsKeyword_7_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SmartHomeGrammarAccess) access;
		match_Device_ActionsKeyword_5_q = new TokenAlias(false, true, grammarAccess.getDeviceAccess().getActionsKeyword_5());
		match_Device_ConstraintsKeyword_7_q = new TokenAlias(false, true, grammarAccess.getDeviceAccess().getConstraintsKeyword_7());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Device_ActionsKeyword_5_q.equals(syntax))
				emit_Device_ActionsKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Device_ConstraintsKeyword_7_q.equals(syntax))
				emit_Device_ConstraintsKeyword_7_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'Actions:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID 'where' 'properties:' (ambiguity) 'constraints:'? (rule end)
	 *     name=ID 'where' 'properties:' (ambiguity) 'constraints:'? exp+=Exp
	 *     name=ID 'where' 'properties:' (ambiguity) actions+=Action
	 *     properties+=Property (ambiguity) 'constraints:'? (rule end)
	 *     properties+=Property (ambiguity) 'constraints:'? exp+=Exp
	 *     properties+=Property (ambiguity) actions+=Action
	 
	 * </pre>
	 */
	protected void emit_Device_ActionsKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'constraints:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     actions+=Action (ambiguity) (rule end)
	 *     actions+=Action (ambiguity) exp+=Exp
	 *     name=ID 'where' 'properties:' 'Actions:'? (ambiguity) (rule end)
	 *     name=ID 'where' 'properties:' 'Actions:'? (ambiguity) exp+=Exp
	 *     properties+=Property 'Actions:'? (ambiguity) (rule end)
	 *     properties+=Property 'Actions:'? (ambiguity) exp+=Exp
	 
	 * </pre>
	 */
	protected void emit_Device_ConstraintsKeyword_7_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
