/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class SmartHomeLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public SmartHomeLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
