/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.smarthome.ui.internal.SmarthomeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmartHomeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SmarthomeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SmarthomeActivator activator = SmarthomeActivator.getInstance();
		return activator != null ? activator.getInjector(SmarthomeActivator.ORG_XTEXT_EXAMPLE_SMARTHOME_SMARTHOME) : null;
	}

}
