/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.smarthome.smartHome.DeviceInheritance;
import org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails;
import org.xtext.example.smarthome.smartHome.SmartHomePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Device Inheritance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceImpl#getInheritances <em>Inheritances</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeviceInheritanceImpl extends MinimalEObjectImpl.Container implements DeviceInheritance
{
  /**
   * The cached value of the '{@link #getInheritances() <em>Inheritances</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInheritances()
   * @generated
   * @ordered
   */
  protected EList<DeviceInheritanceDetails> inheritances;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeviceInheritanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmartHomePackage.Literals.DEVICE_INHERITANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DeviceInheritanceDetails> getInheritances()
  {
    if (inheritances == null)
    {
      inheritances = new EObjectContainmentEList<DeviceInheritanceDetails>(DeviceInheritanceDetails.class, this, SmartHomePackage.DEVICE_INHERITANCE__INHERITANCES);
    }
    return inheritances;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmartHomePackage.DEVICE_INHERITANCE__INHERITANCES:
        return ((InternalEList<?>)getInheritances()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmartHomePackage.DEVICE_INHERITANCE__INHERITANCES:
        return getInheritances();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmartHomePackage.DEVICE_INHERITANCE__INHERITANCES:
        getInheritances().clear();
        getInheritances().addAll((Collection<? extends DeviceInheritanceDetails>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmartHomePackage.DEVICE_INHERITANCE__INHERITANCES:
        getInheritances().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmartHomePackage.DEVICE_INHERITANCE__INHERITANCES:
        return inheritances != null && !inheritances.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DeviceInheritanceImpl
