/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.smarthome.smartHome.Room;
import org.xtext.example.smarthome.smartHome.RoomInheritanceDetails;
import org.xtext.example.smarthome.smartHome.SmartHomePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Room Inheritance Details</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.impl.RoomInheritanceDetailsImpl#getRoomChild <em>Room Child</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.impl.RoomInheritanceDetailsImpl#getRoomParent <em>Room Parent</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RoomInheritanceDetailsImpl extends MinimalEObjectImpl.Container implements RoomInheritanceDetails
{
  /**
   * The cached value of the '{@link #getRoomChild() <em>Room Child</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoomChild()
   * @generated
   * @ordered
   */
  protected Room roomChild;

  /**
   * The cached value of the '{@link #getRoomParent() <em>Room Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoomParent()
   * @generated
   * @ordered
   */
  protected Room roomParent;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RoomInheritanceDetailsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmartHomePackage.Literals.ROOM_INHERITANCE_DETAILS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Room getRoomChild()
  {
    if (roomChild != null && roomChild.eIsProxy())
    {
      InternalEObject oldRoomChild = (InternalEObject)roomChild;
      roomChild = (Room)eResolveProxy(oldRoomChild);
      if (roomChild != oldRoomChild)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_CHILD, oldRoomChild, roomChild));
      }
    }
    return roomChild;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Room basicGetRoomChild()
  {
    return roomChild;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRoomChild(Room newRoomChild)
  {
    Room oldRoomChild = roomChild;
    roomChild = newRoomChild;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_CHILD, oldRoomChild, roomChild));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Room getRoomParent()
  {
    if (roomParent != null && roomParent.eIsProxy())
    {
      InternalEObject oldRoomParent = (InternalEObject)roomParent;
      roomParent = (Room)eResolveProxy(oldRoomParent);
      if (roomParent != oldRoomParent)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_PARENT, oldRoomParent, roomParent));
      }
    }
    return roomParent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Room basicGetRoomParent()
  {
    return roomParent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRoomParent(Room newRoomParent)
  {
    Room oldRoomParent = roomParent;
    roomParent = newRoomParent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_PARENT, oldRoomParent, roomParent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_CHILD:
        if (resolve) return getRoomChild();
        return basicGetRoomChild();
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_PARENT:
        if (resolve) return getRoomParent();
        return basicGetRoomParent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_CHILD:
        setRoomChild((Room)newValue);
        return;
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_PARENT:
        setRoomParent((Room)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_CHILD:
        setRoomChild((Room)null);
        return;
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_PARENT:
        setRoomParent((Room)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_CHILD:
        return roomChild != null;
      case SmartHomePackage.ROOM_INHERITANCE_DETAILS__ROOM_PARENT:
        return roomParent != null;
    }
    return super.eIsSet(featureID);
  }

} //RoomInheritanceDetailsImpl
