/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class SmartHomeProposalProvider extends AbstractSmartHomeProposalProvider {
}
