/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Controller</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Controller#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Controller#getRooms <em>Rooms</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Controller#getRoomInheritance <em>Room Inheritance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getController()
 * @model
 * @generated
 */
public interface Controller extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getController_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.Controller#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Rooms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.Room}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rooms</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getController_Rooms()
   * @model containment="true"
   * @generated
   */
  EList<Room> getRooms();

  /**
   * Returns the value of the '<em><b>Room Inheritance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Room Inheritance</em>' containment reference.
   * @see #setRoomInheritance(RoomInheritance)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getController_RoomInheritance()
   * @model containment="true"
   * @generated
   */
  RoomInheritance getRoomInheritance();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.Controller#getRoomInheritance <em>Room Inheritance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Room Inheritance</em>' containment reference.
   * @see #getRoomInheritance()
   * @generated
   */
  void setRoomInheritance(RoomInheritance value);

} // Controller
