/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Device#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Device#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Device#getActions <em>Actions</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Device#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDevice()
 * @model
 * @generated
 */
public interface Device extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDevice_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.Device#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDevice_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDevice_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDevice_Exp()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExp();

} // Device
