/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device Inheritance Details</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceChild <em>Device Child</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceParent <em>Device Parent</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDeviceInheritanceDetails()
 * @model
 * @generated
 */
public interface DeviceInheritanceDetails extends EObject
{
  /**
   * Returns the value of the '<em><b>Device Child</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device Child</em>' reference.
   * @see #setDeviceChild(Device)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDeviceInheritanceDetails_DeviceChild()
   * @model
   * @generated
   */
  Device getDeviceChild();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceChild <em>Device Child</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device Child</em>' reference.
   * @see #getDeviceChild()
   * @generated
   */
  void setDeviceChild(Device value);

  /**
   * Returns the value of the '<em><b>Device Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device Parent</em>' reference.
   * @see #setDeviceParent(Device)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getDeviceInheritanceDetails_DeviceParent()
   * @model
   * @generated
   */
  Device getDeviceParent();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceParent <em>Device Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device Parent</em>' reference.
   * @see #getDeviceParent()
   * @generated
   */
  void setDeviceParent(Device value);

} // DeviceInheritanceDetails
