/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parenthesis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Parenthesis#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getParenthesis()
 * @model
 * @generated
 */
public interface Parenthesis extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getParenthesis_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.Parenthesis#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

} // Parenthesis
