/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Room Inheritance Details</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomChild <em>Room Child</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomParent <em>Room Parent</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoomInheritanceDetails()
 * @model
 * @generated
 */
public interface RoomInheritanceDetails extends EObject
{
  /**
   * Returns the value of the '<em><b>Room Child</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Room Child</em>' reference.
   * @see #setRoomChild(Room)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoomInheritanceDetails_RoomChild()
   * @model
   * @generated
   */
  Room getRoomChild();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomChild <em>Room Child</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Room Child</em>' reference.
   * @see #getRoomChild()
   * @generated
   */
  void setRoomChild(Room value);

  /**
   * Returns the value of the '<em><b>Room Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Room Parent</em>' reference.
   * @see #setRoomParent(Room)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoomInheritanceDetails_RoomParent()
   * @model
   * @generated
   */
  Room getRoomParent();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomParent <em>Room Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Room Parent</em>' reference.
   * @see #getRoomParent()
   * @generated
   */
  void setRoomParent(Room value);

} // RoomInheritanceDetails
