/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Room</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Room#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Room#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Room#getDevices <em>Devices</em>}</li>
 *   <li>{@link org.xtext.example.smarthome.smartHome.Room#getDeviceInheritance <em>Device Inheritance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoom()
 * @model
 * @generated
 */
public interface Room extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoom_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.Room#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoom_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

  /**
   * Returns the value of the '<em><b>Devices</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.Device}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Devices</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoom_Devices()
   * @model containment="true"
   * @generated
   */
  EList<Device> getDevices();

  /**
   * Returns the value of the '<em><b>Device Inheritance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device Inheritance</em>' containment reference.
   * @see #setDeviceInheritance(DeviceInheritance)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoom_DeviceInheritance()
   * @model containment="true"
   * @generated
   */
  DeviceInheritance getDeviceInheritance();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.Room#getDeviceInheritance <em>Device Inheritance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device Inheritance</em>' containment reference.
   * @see #getDeviceInheritance()
   * @generated
   */
  void setDeviceInheritance(DeviceInheritance value);

} // Room
