/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Room Inheritance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.RoomInheritance#getInheritances <em>Inheritances</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoomInheritance()
 * @model
 * @generated
 */
public interface RoomInheritance extends EObject
{
  /**
   * Returns the value of the '<em><b>Inheritances</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inheritances</em>' containment reference list.
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getRoomInheritance_Inheritances()
   * @model containment="true"
   * @generated
   */
  EList<RoomInheritanceDetails> getInheritances();

} // RoomInheritance
