/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.smarthome.smartHome.SmartHomeFactory
 * @model kind="package"
 * @generated
 */
public interface SmartHomePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "smartHome";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/smarthome/SmartHome";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "smartHome";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SmartHomePackage eINSTANCE = org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.ControllerImpl <em>Controller</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.ControllerImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getController()
   * @generated
   */
  int CONTROLLER = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__NAME = 0;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__ROOMS = 1;

  /**
   * The feature id for the '<em><b>Room Inheritance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__ROOM_INHERITANCE = 2;

  /**
   * The number of structural features of the '<em>Controller</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.RoomImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getRoom()
   * @generated
   */
  int ROOM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__PROPERTIES = 1;

  /**
   * The feature id for the '<em><b>Devices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__DEVICES = 2;

  /**
   * The feature id for the '<em><b>Device Inheritance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__DEVICE_INHERITANCE = 3;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.RoomInheritanceImpl <em>Room Inheritance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.RoomInheritanceImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getRoomInheritance()
   * @generated
   */
  int ROOM_INHERITANCE = 2;

  /**
   * The feature id for the '<em><b>Inheritances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_INHERITANCE__INHERITANCES = 0;

  /**
   * The number of structural features of the '<em>Room Inheritance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_INHERITANCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.RoomInheritanceDetailsImpl <em>Room Inheritance Details</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.RoomInheritanceDetailsImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getRoomInheritanceDetails()
   * @generated
   */
  int ROOM_INHERITANCE_DETAILS = 3;

  /**
   * The feature id for the '<em><b>Room Child</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_INHERITANCE_DETAILS__ROOM_CHILD = 0;

  /**
   * The feature id for the '<em><b>Room Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_INHERITANCE_DETAILS__ROOM_PARENT = 1;

  /**
   * The number of structural features of the '<em>Room Inheritance Details</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_INHERITANCE_DETAILS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceImpl <em>Device Inheritance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDeviceInheritance()
   * @generated
   */
  int DEVICE_INHERITANCE = 4;

  /**
   * The feature id for the '<em><b>Inheritances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_INHERITANCE__INHERITANCES = 0;

  /**
   * The number of structural features of the '<em>Device Inheritance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_INHERITANCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceDetailsImpl <em>Device Inheritance Details</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceDetailsImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDeviceInheritanceDetails()
   * @generated
   */
  int DEVICE_INHERITANCE_DETAILS = 5;

  /**
   * The feature id for the '<em><b>Device Child</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_INHERITANCE_DETAILS__DEVICE_CHILD = 0;

  /**
   * The feature id for the '<em><b>Device Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_INHERITANCE_DETAILS__DEVICE_PARENT = 1;

  /**
   * The number of structural features of the '<em>Device Inheritance Details</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_INHERITANCE_DETAILS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.DeviceImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__PROPERTIES = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__ACTIONS = 2;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__EXP = 3;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.ActionImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getAction()
   * @generated
   */
  int ACTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.PropertyImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 8;

  /**
   * The feature id for the '<em><b>Pr Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__PR_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 2;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.DevPropertyImpl <em>Dev Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.DevPropertyImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDevProperty()
   * @generated
   */
  int DEV_PROPERTY = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEV_PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEV_PROPERTY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Dev Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEV_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.ExpressionImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 10;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.TypeImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getType()
   * @generated
   */
  int TYPE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.PropertyTypeImpl <em>Property Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.PropertyTypeImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getPropertyType()
   * @generated
   */
  int PROPERTY_TYPE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Property Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.ANDImpl <em>AND</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.ANDImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getAND()
   * @generated
   */
  int AND = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>AND</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.GTImpl <em>GT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.GTImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getGT()
   * @generated
   */
  int GT = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>GT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.LTImpl <em>LT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.LTImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getLT()
   * @generated
   */
  int LT = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>LT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.MyNumberImpl <em>My Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.MyNumberImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getMyNumber()
   * @generated
   */
  int MY_NUMBER = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_NUMBER__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>My Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_NUMBER_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.VarRefImpl <em>Var Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.VarRefImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getVarRef()
   * @generated
   */
  int VAR_REF = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smarthome.smartHome.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smarthome.smartHome.impl.ParenthesisImpl
   * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getParenthesis()
   * @generated
   */
  int PARENTHESIS = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parenthesis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Controller <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Controller</em>'.
   * @see org.xtext.example.smarthome.smartHome.Controller
   * @generated
   */
  EClass getController();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.Controller#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.Controller#getName()
   * @see #getController()
   * @generated
   */
  EAttribute getController_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.Controller#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.xtext.example.smarthome.smartHome.Controller#getRooms()
   * @see #getController()
   * @generated
   */
  EReference getController_Rooms();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.Controller#getRoomInheritance <em>Room Inheritance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Room Inheritance</em>'.
   * @see org.xtext.example.smarthome.smartHome.Controller#getRoomInheritance()
   * @see #getController()
   * @generated
   */
  EReference getController_RoomInheritance();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.example.smarthome.smartHome.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.Room#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.example.smarthome.smartHome.Room#getProperties()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Properties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.Room#getDevices <em>Devices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Devices</em>'.
   * @see org.xtext.example.smarthome.smartHome.Room#getDevices()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Devices();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.Room#getDeviceInheritance <em>Device Inheritance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Device Inheritance</em>'.
   * @see org.xtext.example.smarthome.smartHome.Room#getDeviceInheritance()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_DeviceInheritance();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.RoomInheritance <em>Room Inheritance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Inheritance</em>'.
   * @see org.xtext.example.smarthome.smartHome.RoomInheritance
   * @generated
   */
  EClass getRoomInheritance();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.RoomInheritance#getInheritances <em>Inheritances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inheritances</em>'.
   * @see org.xtext.example.smarthome.smartHome.RoomInheritance#getInheritances()
   * @see #getRoomInheritance()
   * @generated
   */
  EReference getRoomInheritance_Inheritances();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails <em>Room Inheritance Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Inheritance Details</em>'.
   * @see org.xtext.example.smarthome.smartHome.RoomInheritanceDetails
   * @generated
   */
  EClass getRoomInheritanceDetails();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomChild <em>Room Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room Child</em>'.
   * @see org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomChild()
   * @see #getRoomInheritanceDetails()
   * @generated
   */
  EReference getRoomInheritanceDetails_RoomChild();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomParent <em>Room Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Room Parent</em>'.
   * @see org.xtext.example.smarthome.smartHome.RoomInheritanceDetails#getRoomParent()
   * @see #getRoomInheritanceDetails()
   * @generated
   */
  EReference getRoomInheritanceDetails_RoomParent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.DeviceInheritance <em>Device Inheritance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Inheritance</em>'.
   * @see org.xtext.example.smarthome.smartHome.DeviceInheritance
   * @generated
   */
  EClass getDeviceInheritance();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.DeviceInheritance#getInheritances <em>Inheritances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inheritances</em>'.
   * @see org.xtext.example.smarthome.smartHome.DeviceInheritance#getInheritances()
   * @see #getDeviceInheritance()
   * @generated
   */
  EReference getDeviceInheritance_Inheritances();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails <em>Device Inheritance Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Inheritance Details</em>'.
   * @see org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails
   * @generated
   */
  EClass getDeviceInheritanceDetails();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceChild <em>Device Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device Child</em>'.
   * @see org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceChild()
   * @see #getDeviceInheritanceDetails()
   * @generated
   */
  EReference getDeviceInheritanceDetails_DeviceChild();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceParent <em>Device Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device Parent</em>'.
   * @see org.xtext.example.smarthome.smartHome.DeviceInheritanceDetails#getDeviceParent()
   * @see #getDeviceInheritanceDetails()
   * @generated
   */
  EReference getDeviceInheritanceDetails_DeviceParent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.example.smarthome.smartHome.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.Device#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.example.smarthome.smartHome.Device#getProperties()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Properties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.Device#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.smarthome.smartHome.Device#getActions()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Actions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smarthome.smartHome.Device#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see org.xtext.example.smarthome.smartHome.Device#getExp()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.smarthome.smartHome.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.example.smarthome.smartHome.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.Property#getPrType <em>Pr Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pr Type</em>'.
   * @see org.xtext.example.smarthome.smartHome.Property#getPrType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_PrType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.smarthome.smartHome.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.DevProperty <em>Dev Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dev Property</em>'.
   * @see org.xtext.example.smarthome.smartHome.DevProperty
   * @generated
   */
  EClass getDevProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.DevProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.DevProperty#getName()
   * @see #getDevProperty()
   * @generated
   */
  EAttribute getDevProperty_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.DevProperty#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.smarthome.smartHome.DevProperty#getType()
   * @see #getDevProperty()
   * @generated
   */
  EReference getDevProperty_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.smarthome.smartHome.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.smarthome.smartHome.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.PropertyType <em>Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Type</em>'.
   * @see org.xtext.example.smarthome.smartHome.PropertyType
   * @generated
   */
  EClass getPropertyType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.PropertyType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smarthome.smartHome.PropertyType#getName()
   * @see #getPropertyType()
   * @generated
   */
  EAttribute getPropertyType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.AND <em>AND</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AND</em>'.
   * @see org.xtext.example.smarthome.smartHome.AND
   * @generated
   */
  EClass getAND();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.AND#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.smarthome.smartHome.AND#getLeft()
   * @see #getAND()
   * @generated
   */
  EReference getAND_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.AND#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.smarthome.smartHome.AND#getRight()
   * @see #getAND()
   * @generated
   */
  EReference getAND_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.GT <em>GT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GT</em>'.
   * @see org.xtext.example.smarthome.smartHome.GT
   * @generated
   */
  EClass getGT();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.GT#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.smarthome.smartHome.GT#getLeft()
   * @see #getGT()
   * @generated
   */
  EReference getGT_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.GT#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.smarthome.smartHome.GT#getRight()
   * @see #getGT()
   * @generated
   */
  EReference getGT_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.LT <em>LT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LT</em>'.
   * @see org.xtext.example.smarthome.smartHome.LT
   * @generated
   */
  EClass getLT();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.LT#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.smarthome.smartHome.LT#getLeft()
   * @see #getLT()
   * @generated
   */
  EReference getLT_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.LT#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.smarthome.smartHome.LT#getRight()
   * @see #getLT()
   * @generated
   */
  EReference getLT_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.MyNumber <em>My Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My Number</em>'.
   * @see org.xtext.example.smarthome.smartHome.MyNumber
   * @generated
   */
  EClass getMyNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smarthome.smartHome.MyNumber#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.smarthome.smartHome.MyNumber#getValue()
   * @see #getMyNumber()
   * @generated
   */
  EAttribute getMyNumber_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.VarRef <em>Var Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Ref</em>'.
   * @see org.xtext.example.smarthome.smartHome.VarRef
   * @generated
   */
  EClass getVarRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smarthome.smartHome.VarRef#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Value</em>'.
   * @see org.xtext.example.smarthome.smartHome.VarRef#getValue()
   * @see #getVarRef()
   * @generated
   */
  EReference getVarRef_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smarthome.smartHome.Parenthesis <em>Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenthesis</em>'.
   * @see org.xtext.example.smarthome.smartHome.Parenthesis
   * @generated
   */
  EClass getParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smarthome.smartHome.Parenthesis#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.smarthome.smartHome.Parenthesis#getValue()
   * @see #getParenthesis()
   * @generated
   */
  EReference getParenthesis_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SmartHomeFactory getSmartHomeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.ControllerImpl <em>Controller</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.ControllerImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getController()
     * @generated
     */
    EClass CONTROLLER = eINSTANCE.getController();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROLLER__NAME = eINSTANCE.getController_Name();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROLLER__ROOMS = eINSTANCE.getController_Rooms();

    /**
     * The meta object literal for the '<em><b>Room Inheritance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROLLER__ROOM_INHERITANCE = eINSTANCE.getController_RoomInheritance();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.RoomImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__PROPERTIES = eINSTANCE.getRoom_Properties();

    /**
     * The meta object literal for the '<em><b>Devices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__DEVICES = eINSTANCE.getRoom_Devices();

    /**
     * The meta object literal for the '<em><b>Device Inheritance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__DEVICE_INHERITANCE = eINSTANCE.getRoom_DeviceInheritance();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.RoomInheritanceImpl <em>Room Inheritance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.RoomInheritanceImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getRoomInheritance()
     * @generated
     */
    EClass ROOM_INHERITANCE = eINSTANCE.getRoomInheritance();

    /**
     * The meta object literal for the '<em><b>Inheritances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_INHERITANCE__INHERITANCES = eINSTANCE.getRoomInheritance_Inheritances();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.RoomInheritanceDetailsImpl <em>Room Inheritance Details</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.RoomInheritanceDetailsImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getRoomInheritanceDetails()
     * @generated
     */
    EClass ROOM_INHERITANCE_DETAILS = eINSTANCE.getRoomInheritanceDetails();

    /**
     * The meta object literal for the '<em><b>Room Child</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_INHERITANCE_DETAILS__ROOM_CHILD = eINSTANCE.getRoomInheritanceDetails_RoomChild();

    /**
     * The meta object literal for the '<em><b>Room Parent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_INHERITANCE_DETAILS__ROOM_PARENT = eINSTANCE.getRoomInheritanceDetails_RoomParent();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceImpl <em>Device Inheritance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDeviceInheritance()
     * @generated
     */
    EClass DEVICE_INHERITANCE = eINSTANCE.getDeviceInheritance();

    /**
     * The meta object literal for the '<em><b>Inheritances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_INHERITANCE__INHERITANCES = eINSTANCE.getDeviceInheritance_Inheritances();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceDetailsImpl <em>Device Inheritance Details</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.DeviceInheritanceDetailsImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDeviceInheritanceDetails()
     * @generated
     */
    EClass DEVICE_INHERITANCE_DETAILS = eINSTANCE.getDeviceInheritanceDetails();

    /**
     * The meta object literal for the '<em><b>Device Child</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_INHERITANCE_DETAILS__DEVICE_CHILD = eINSTANCE.getDeviceInheritanceDetails_DeviceChild();

    /**
     * The meta object literal for the '<em><b>Device Parent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_INHERITANCE_DETAILS__DEVICE_PARENT = eINSTANCE.getDeviceInheritanceDetails_DeviceParent();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.DeviceImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__PROPERTIES = eINSTANCE.getDevice_Properties();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__ACTIONS = eINSTANCE.getDevice_Actions();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__EXP = eINSTANCE.getDevice_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.ActionImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.PropertyImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Pr Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__PR_TYPE = eINSTANCE.getProperty_PrType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.DevPropertyImpl <em>Dev Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.DevPropertyImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getDevProperty()
     * @generated
     */
    EClass DEV_PROPERTY = eINSTANCE.getDevProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEV_PROPERTY__NAME = eINSTANCE.getDevProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEV_PROPERTY__TYPE = eINSTANCE.getDevProperty_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.ExpressionImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.TypeImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.PropertyTypeImpl <em>Property Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.PropertyTypeImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getPropertyType()
     * @generated
     */
    EClass PROPERTY_TYPE = eINSTANCE.getPropertyType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_TYPE__NAME = eINSTANCE.getPropertyType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.ANDImpl <em>AND</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.ANDImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getAND()
     * @generated
     */
    EClass AND = eINSTANCE.getAND();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAND_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAND_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.GTImpl <em>GT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.GTImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getGT()
     * @generated
     */
    EClass GT = eINSTANCE.getGT();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__LEFT = eINSTANCE.getGT_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__RIGHT = eINSTANCE.getGT_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.LTImpl <em>LT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.LTImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getLT()
     * @generated
     */
    EClass LT = eINSTANCE.getLT();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__LEFT = eINSTANCE.getLT_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__RIGHT = eINSTANCE.getLT_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.MyNumberImpl <em>My Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.MyNumberImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getMyNumber()
     * @generated
     */
    EClass MY_NUMBER = eINSTANCE.getMyNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MY_NUMBER__VALUE = eINSTANCE.getMyNumber_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.VarRefImpl <em>Var Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.VarRefImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getVarRef()
     * @generated
     */
    EClass VAR_REF = eINSTANCE.getVarRef();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_REF__VALUE = eINSTANCE.getVarRef_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.smarthome.smartHome.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smarthome.smartHome.impl.ParenthesisImpl
     * @see org.xtext.example.smarthome.smartHome.impl.SmartHomePackageImpl#getParenthesis()
     * @generated
     */
    EClass PARENTHESIS = eINSTANCE.getParenthesis();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESIS__VALUE = eINSTANCE.getParenthesis_Value();

  }

} //SmartHomePackage
