/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.smartHome;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smarthome.smartHome.VarRef#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getVarRef()
 * @model
 * @generated
 */
public interface VarRef extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(Property)
   * @see org.xtext.example.smarthome.smartHome.SmartHomePackage#getVarRef_Value()
   * @model
   * @generated
   */
  Property getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.smarthome.smartHome.VarRef#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Property value);

} // VarRef
