/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeStandaloneSetup extends SmartHomeStandaloneSetupGenerated {
  public static void doSetup() {
    new SmartHomeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
