/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeRuntimeModule extends AbstractSmartHomeRuntimeModule {
}
