/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmartHomeScopeProvider extends DelegatingScopeProvider {
}
