/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmartHomeStandaloneSetup extends SmartHomeStandaloneSetupGenerated {

	def static void doSetup() {
		new SmartHomeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
