/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.smarthome.SmartHomeRuntimeModule;
import org.xtext.example.smarthome.SmartHomeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SmartHomeIdeSetup extends SmartHomeStandaloneSetup {
  @Override
  public Injector createInjector() {
    SmartHomeRuntimeModule _smartHomeRuntimeModule = new SmartHomeRuntimeModule();
    SmartHomeIdeModule _smartHomeIdeModule = new SmartHomeIdeModule();
    return Guice.createInjector(Modules2.mixin(_smartHomeRuntimeModule, _smartHomeIdeModule));
  }
}
