/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SmartHomeIdeModule extends AbstractSmartHomeIdeModule {
}
