/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.smarthome.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.smarthome.ui.internal.SmarthomeActivator;

public class SmartHomeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmarthomeActivator.getInstance().getInjector("org.xtext.example.smarthome.SmartHome");
	}

}
